In [1]:
import os
import numpy as np
txt_dir = r'Data'
txt_files = [os.path.join(txt_dir, f) for f in os.listdir(txt_dir) if f.endswith('.txt') and os.path.isfile(os.path.join(txt_dir, f))]

# list of province in indonesia
province = np.array([str(f)[8:-4] for f in txt_files])

print('Number of province:', len(province))
print(province)

Number of province: 34
['Aceh' 'Sumatera Utara' 'Riau' 'Kepulauan Riau' 'Bangka Belitung'
 'Sumatera Barat' 'Jambi' 'Sumatera Selatan' 'Bengkulu' 'Lampung'
 'Kalimantan Barat' 'Kalimantan Selatan' 'Kalimantan Tengah'
 'Kalimantan Timur' 'Kalimantan Utara' 'DKI Jakarta' 'Banten' 'Jawa Barat'
 'Jawa Tengah' 'D.I. Yogyakarta' 'Jawa Timur' 'Bali' 'Sulawesi Utara'
 'Sulawesi Tengah' 'Gorontalo' 'Sulawesi Selatan' 'Sulawesi Tenggara'
 'Sulawesi Barat' 'Maluku' 'Maluku Utara' 'Papua' 'Papua Barat' 'NTB'
 'NTT']

In [2]:
import pandas as pd 


production_data = {}

export_data = {}


for i, t in enumerate(txt_files):

    ds = pd.read_csv(t, sep=';')
    ds = ds.iloc[:, ~ds.columns.str.contains('^Unnamed')]
    ds = ds.iloc[:-1,:]
    ds['Tahun'] = ds['Tahun'].astype(int)

    export_data[province[i]] = ds


    # Remove the last row
    ds = ds[(ds['Tahun'] >= 2025) & (ds['Tahun'] <= 2034)]

    production = ds['Produksi(GWh)']
    year = ds['Tahun']

    production_data[province[i]] = dict(zip(year, production))

df = pd.DataFrame(production_data)

df = df.transpose()
df.index.name = 'Province' 


df

,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034
Province,,,,,,,,,,
Aceh,4263.00,4385.00,4541.0,4720.00,4893.00,5302.00,5487.00,5574.00,7086.00,7273.00
Sumatera Utara,16034.00,16508.00,17179.0,17931.00,18906.00,19878.00,20896.00,21964.00,23086.00,24265.00
Riau,9545.00,9719.00,10141.0,10624.00,11028.00,11446.00,11872.00,12335.00,13178.00,14364.00
Kepulauan Riau,1171.00,1217.00,1277.0,1342.00,1410.00,1486.00,6039.00,6125.00,6218.00,6316.00
Bangka Belitung,2096.00,2222.00,2352.0,2486.00,2620.00,2756.00,2895.00,3035.00,3177.00,3321.00
Sumatera Barat,4472.00,4647.00,4826.0,5023.00,5270.00,5534.00,5813.00,6112.00,6431.00,6770.00
Jambi,3000.00,3147.00,4863.0,5031.00,5189.00,5352.00,5520.00,5694.00,5873.00,6058.00
Sumatera Selatan,8053.00,8524.00,8942.0,9397.00,9965.00,10682.00,11212.00,11744.00,12665.00,13277.00
Bengkulu,1381.00,1439.00,1510.0,1588.00,1667.00,1749.00,1836.00,1926.00,2021.00,2119.00
Lampung,7368.00,7741.00,8151.0,8567.00,8996.00,9443.00,9849.00,10255.00,10716.00,11192.00
Kalimantan Barat,4082.00,4288.00,4461.0,4646.00,4823.00,5005.00,5191.00,5384.00,5581.00,5785.00
Kalimantan Selatan,4774.00,5076.00,5350.0,5610.00,5876.00,6150.00,6436.00,6732.00,7039.00,7357.00
Kalimantan Tengah,2438.00,2585.00,2735.0,2889.00,3047.00,3214.00,3390.00,3576.00,3775.00,3988.00
Kalimantan Timur,6856.00,7685.00,9015.0,9188.00,10344.00,10993.00,11418.00,13158.00,13661.00,13965.00
Kalimantan Utara,749.00,789.00,831.0,875.00,921.00,970.00,1021.00,1076.00,1124.00,1186.00
DKI Jakarta,41666.00,42845.00,44533.0,46203.00,48692.00,50335.00,52201.00,54094.00,56134.00,58114.00
Banten,31122.00,31835.00,32863.0,33895.00,34930.00,36010.00,37156.00,38334.00,39565.00,40905.00
Jawa Barat,70743.00,75161.00,78850.0,82418.00,84818.00,88932.00,91476.00,94627.00,97571.00,100404.00
Jawa Tengah,35683.00,37350.00,39078.0,41208.00,43319.00,45794.00,48993.00,51232.00,53766.00,56385.00
D.I. Yogyakarta,4318.00,4643.00,4975.0,5335.00,5721.00,6134.00,6574.00,7047.00,7555.00,8099.00
Jawa Timur,49562.00,51922.00,54341.0,56339.00,58626.00,59884.00,61554.00,63198.00,65277.00,67261.00
Bali,8341.00,8975.00,9537.0,10161.00,10864.00,11613.00,12391.00,13233.00,14118.00,15079.00
Sulawesi Utara,2674.00,2823.00,3252.0,3457.00,3666.00,3882.00,4049.00,4222.00,4403.00,4592.00
Sulawesi Tengah,2437.00,2568.00,2989.0,3472.00,4173.00,5514.00,7163.00,8675.00,9613.00,9906.00
Gorontalo,965.00,1047.00,1227.0,1657.00,1737.00,1896.00,1980.00,2047.00,2117.00,2210.00
Sulawesi Selatan,10959.00,11461.00,12230.0,12864.00,13620.00,14882.00,16345.00,17750.00,18849.00,19602.00
Sulawesi Tenggara,2883.90,4059.10,5399.0,5932.30,6335.30,7433.50,8785.20,10020.70,10781.00,11007.40
Sulawesi Barat,622.92,665.68,710.3,756.72,804.96,856.04,910.24,967.59,1028.59,1093.47
Maluku,988.00,1043.00,1102.0,1165.00,1229.00,1294.00,1362.00,1433.00,1507.00,1583.00
Maluku Utara,1391.30,1453.90,1520.6,2109.20,2180.50,2287.60,2383.50,2754.40,3435.80,3529.30
Papua,1815.00,1926.00,2038.0,2150.00,2263.00,2377.00,2493.00,2611.00,2732.00,2854.00
Papua Barat,854.00,905.00,956.0,1010.00,1065.00,1123.00,1184.00,1247.00,1314.00,1384.00
NTB,3433.00,3663.00,3890.0,4140.00,4377.00,4633.00,4896.00,5150.00,5411.00,5679.00
NTT,1831.00,2003.00,2132.0,2318.00,2504.00,2688.00,2881.00,3084.00,3305.00,3534.00

In [3]:
region_map = {
    'Aceh': 'Sumatera',
    'Bali': 'Jawa-Bali',
    'Bangka Belitung': 'Sumatera',
    'Banten': 'Jawa-Bali',
    'Bengkulu': 'Sumatera',
    'D.I. Yogyakarta': 'Jawa-Bali',
    'Gorontalo': 'Sulawesi',
    'DKI Jakarta': 'Jawa-Bali',
    'Jambi': 'Sumatera',
    'Jawa Barat': 'Jawa-Bali',
    'Jawa Tengah': 'Jawa-Bali',
    'Jawa Timur': 'Jawa-Bali',
    'Kalimantan Barat': 'Kalimantan',
    'Kalimantan Selatan': 'Kalimantan',
    'Kalimantan Tengah': 'Kalimantan',
    'Kalimantan Timur': 'Kalimantan',
    'Kalimantan Utara': 'Kalimantan',
    'Kepulauan Riau': 'Sumatera',
    'Lampung': 'Sumatera',
    'Maluku': 'Maluku',
    'Maluku Utara': 'Maluku',
    'NTB': 'NTB',
    'NTT': 'NTT',
    'Papua': 'Papua',
    'Papua Barat': 'Papua',
    'Riau': 'Sumatera',
    'Sulawesi Barat': 'Sulawesi',
    'Sulawesi Selatan': 'Sulawesi',
    'Sulawesi Tengah': 'Sulawesi',
    'Sulawesi Tenggara': 'Sulawesi',
    'Sulawesi Utara': 'Sulawesi',
    'Sumatera Barat': 'Sumatera',
    'Sumatera Selatan': 'Sumatera',
    'Sumatera Utara': 'Sumatera'
}

In [4]:
df_with_region = df.copy()
df_with_region['Region'] = [region_map[prov] for prov in df_with_region.index]
cols = ['Region'] + [col for col in df_with_region.columns if col != 'Region']
df_with_region = df_with_region[cols]
df_with_region.sort_values(by='Region')

,Region,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034
Province,,,,,,,,,,,
Banten,Jawa-Bali,31122.00,31835.00,32863.0,33895.00,34930.00,36010.00,37156.00,38334.00,39565.00,40905.00
Bali,Jawa-Bali,8341.00,8975.00,9537.0,10161.00,10864.00,11613.00,12391.00,13233.00,14118.00,15079.00
Jawa Timur,Jawa-Bali,49562.00,51922.00,54341.0,56339.00,58626.00,59884.00,61554.00,63198.00,65277.00,67261.00
D.I. Yogyakarta,Jawa-Bali,4318.00,4643.00,4975.0,5335.00,5721.00,6134.00,6574.00,7047.00,7555.00,8099.00
Jawa Tengah,Jawa-Bali,35683.00,37350.00,39078.0,41208.00,43319.00,45794.00,48993.00,51232.00,53766.00,56385.00
Jawa Barat,Jawa-Bali,70743.00,75161.00,78850.0,82418.00,84818.00,88932.00,91476.00,94627.00,97571.00,100404.00
DKI Jakarta,Jawa-Bali,41666.00,42845.00,44533.0,46203.00,48692.00,50335.00,52201.00,54094.00,56134.00,58114.00
Kalimantan Barat,Kalimantan,4082.00,4288.00,4461.0,4646.00,4823.00,5005.00,5191.00,5384.00,5581.00,5785.00
Kalimantan Selatan,Kalimantan,4774.00,5076.00,5350.0,5610.00,5876.00,6150.00,6436.00,6732.00,7039.00,7357.00
Kalimantan Tengah,Kalimantan,2438.00,2585.00,2735.0,2889.00,3047.00,3214.00,3390.00,3576.00,3775.00,3988.00
Kalimantan Timur,Kalimantan,6856.00,7685.00,9015.0,9188.00,10344.00,10993.00,11418.00,13158.00,13661.00,13965.00
Kalimantan Utara,Kalimantan,749.00,789.00,831.0,875.00,921.00,970.00,1021.00,1076.00,1124.00,1186.00
Maluku Utara,Maluku,1391.30,1453.90,1520.6,2109.20,2180.50,2287.60,2383.50,2754.40,3435.80,3529.30
Maluku,Maluku,988.00,1043.00,1102.0,1165.00,1229.00,1294.00,1362.00,1433.00,1507.00,1583.00
NTB,NTB,3433.00,3663.00,3890.0,4140.00,4377.00,4633.00,4896.00,5150.00,5411.00,5679.00
NTT,NTT,1831.00,2003.00,2132.0,2318.00,2504.00,2688.00,2881.00,3084.00,3305.00,3534.00
Papua Barat,Papua,854.00,905.00,956.0,1010.00,1065.00,1123.00,1184.00,1247.00,1314.00,1384.00
Papua,Papua,1815.00,1926.00,2038.0,2150.00,2263.00,2377.00,2493.00,2611.00,2732.00,2854.00
Gorontalo,Sulawesi,965.00,1047.00,1227.0,1657.00,1737.00,1896.00,1980.00,2047.00,2117.00,2210.00
Sulawesi Barat,Sulawesi,622.92,665.68,710.3,756.72,804.96,856.04,910.24,967.59,1028.59,1093.47
Sulawesi Utara,Sulawesi,2674.00,2823.00,3252.0,3457.00,3666.00,3882.00,4049.00,4222.00,4403.00,4592.00
Sulawesi Tengah,Sulawesi,2437.00,2568.00,2989.0,3472.00,4173.00,5514.00,7163.00,8675.00,9613.00,9906.00
Sulawesi Tenggara,Sulawesi,2883.90,4059.10,5399.0,5932.30,6335.30,7433.50,8785.20,10020.70,10781.00,11007.40
Sulawesi Selatan,Sulawesi,10959.00,11461.00,12230.0,12864.00,13620.00,14882.00,16345.00,17750.00,18849.00,19602.00
Sumatera Utara,Sumatera,16034.00,16508.00,17179.0,17931.00,18906.00,19878.00,20896.00,21964.00,23086.00,24265.00
Riau,Sumatera,9545.00,9719.00,10141.0,10624.00,11028.00,11446.00,11872.00,12335.00,13178.00,14364.00
Bengkulu,Sumatera,1381.00,1439.00,1510.0,1588.00,1667.00,1749.00,1836.00,1926.00,2021.00,2119.00
Kepulauan Riau,Sumatera,1171.00,1217.00,1277.0,1342.00,1410.00,1486.00,6039.00,6125.00,6218.00,6316.00
Bangka Belitung,Sumatera,2096.00,2222.00,2352.0,2486.00,2620.00,2756.00,2895.00,3035.00,3177.00,3321.00
Sumatera Barat,Sumatera,4472.00,4647.00,4826.0,5023.00,5270.00,5534.00,5813.00,6112.00,6431.00,6770.00
Jambi,Sumatera,3000.00,3147.00,4863.0,5031.00,5189.00,5352.00,5520.00,5694.00,5873.00,6058.00
Sumatera Selatan,Sumatera,8053.00,8524.00,8942.0,9397.00,9965.00,10682.00,11212.00,11744.00,12665.00,13277.00
Lampung,Sumatera,7368.00,7741.00,8151.0,8567.00,8996.00,9443.00,9849.00,10255.00,10716.00,11192.00
Aceh,Sumatera,4263.00,4385.00,4541.0,4720.00,4893.00,5302.00,5487.00,5574.00,7086.00,7273.00

In [5]:
regional_demand = df_with_region.groupby('Region').sum()
regional_demand

,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034
Region,,,,,,,,,,
Jawa-Bali,241435.00,252731.00,264177.0,275559.00,286970.00,298702.00,310345.00,321765.00,333986.00,346247.00
Kalimantan,18899.00,20423.00,22392.0,23208.00,25011.00,26332.00,27456.00,29926.00,31180.00,32281.00
Maluku,2379.30,2496.90,2622.6,3274.20,3409.50,3581.60,3745.50,4187.40,4942.80,5112.30
NTB,3433.00,3663.00,3890.0,4140.00,4377.00,4633.00,4896.00,5150.00,5411.00,5679.00
NTT,1831.00,2003.00,2132.0,2318.00,2504.00,2688.00,2881.00,3084.00,3305.00,3534.00
Papua,2669.00,2831.00,2994.0,3160.00,3328.00,3500.00,3677.00,3858.00,4046.00,4238.00
Sulawesi,20541.82,22623.78,25807.3,28139.02,30336.26,34463.54,39232.44,43682.29,46791.59,48410.87
Sumatera,57383.00,59549.00,63782.0,66709.00,69944.00,73628.00,81419.00,84764.00,90451.00,94955.00

In [6]:

# Add the Electricty Demand column to the export data
export_data['PerProvince'] = df_with_region.sort_values(by='Region')
export_data['Recap'] = regional_demand

In [7]:
with pd.ExcelWriter(r'Data Electricity Demand.xlsx', engine='openpyxl', mode='w') as writer:
    for sheet_name, data in export_data.items():
        if sheet_name in ['PerProvince', 'Recap']:
            data.to_excel(writer, sheet_name=sheet_name, index=True)
        else:
            data.to_excel(writer, sheet_name=sheet_name, index=False)